version: "3.8"

services:
  app:
    image: ivanichmel/tg-bot:latest
    pull_policy: never
    container_name: tg_bot_app
    restart: always
    ports:
      - "8080:8080" # Прокидывание порта приложения
    environment:
      - DATABASE_URL=postgres://root:secret@db:5432/finance_bot?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: tg_bot_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: finance_bot
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
