// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Category struct {
	ID               int64     `json:"id"`
	Name             string    `json:"name"`
	Balance          float64   `json:"balance"`
	PermanentBalance float64   `json:"permanent_balance"`
	CreatedAt        time.Time `json:"created_at"`
}
